Pythonify project
opulo-inc/leash pull request #1
Opened 2024-11-04 16:26 UTC by ISOR3X

Hi, I found this project and while I it still seems to be in development I wanted to submit this relatively small PR that makes the API more Python friendly. We use several LumenPnP machines at work with our own internal python gcode software, but I have seen some improvements when using this repository. This PR includes a couple of changes;

- snake_case instead of CamelCase for variables and functions
- Removed the logging file and switching to the stdlib Logging package
- uv instead of poetry
- ruff for formatting and linting
- Correct syntax for comments (useful if you ever want to create documentation)
- Type annotations in some places, though they could definitely be added in more places.

Depending on what the plan is for this repository I'd have some more features I could potentially add.

2024-11-19 06:04 UTC, CoolCat467 requested changes
Overall looks pretty good, but I noticed a few things.

2024-11-19 06:04 UTC, CoolCat467 commented on README.md
> +        except KeyboardInterrupt:
This doesn't look quite right

2024-11-19 06:04 UTC, CoolCat467 commented on pyproject.toml
> -dynamic = ["version"]
Can't say I agree with getting rid of a lot of these fields, especially the license specifier and making the version static. You are also nuking the unit testing configuration data.

2024-11-19 06:04 UTC, CoolCat467 commented on src/leash/__init__.py
> +        self.sm.send(cmd)
Just wanted to mention, much nicer solution here

2024-11-19 06:04 UTC, CoolCat467 commented on src/leash/__init__.py
> +                        ]
Could do
```python
pos = [self.position[v] for v in "xyz"]
```

2024-11-19 06:04 UTC, CoolCat467 commented on src/leash/photon.py
> +            hex_string = hex_string + converted
```python
hex_string += converted
```

2024-11-19 06:04 UTC, CoolCat467 commented on src/leash/photon.py
>              converted = hex(i)[2:]
I have a feeling some of this could be replaced with f-string hex formatting, especially the zero left padding

2024-11-19 06:04 UTC, CoolCat467 commented on src/leash/photon.py
> +        for i in range(int(len(response_string) / 2)):
Do
```python
range(len(response_string) // 2)
```
to do floor division by two instead of float division by two and then flooring to int.
Even better would be to do something like
```python
for index in range(0, len(response_string), 2)
```
instead of manually calculating index, just let range do it for you with the change by value.

2024-11-19 06:04 UTC, CoolCat467 commented on src/leash/photon.py
> +                     ] + payload
Would recommend using tuple literals instead of list literals. Lists imply needing to be modified in place, while tuples are fixed in memory and can therefore be very slightly faster.

2024-11-19 06:04 UTC, CoolCat467 commented on src/leash/photon.py
> +        elif resp is False:
`is` comparisons generally frowned on unless checking if object IDs are identical (ie with `None`), would recommend 
```python
elif not resp:
```
instead

2024-11-19 06:04 UTC, CoolCat467 commented on src/leash/pump.py
> -"""Manager for controlling and reading pressure from pumps
Why are we removing module docstring?

2024-11-19 06:04 UTC, CoolCat467 commented on src/leash/pump.py
> +            if n < 2 ** 15:
`2**15` could be rewritten as `(1 << 15)`, signifies to reader much more about how we are checking 15th bit. And actually, that doesn't make a lot of sense. 2 bytes used, so 16 bits, wherein 16th bit is sign bit, so I think even the original code might be wrong here.

2024-11-19 06:04 UTC, CoolCat467 commented on src/leash/serial.py
> -"""Manager for serial communications
Again, why are we deleting module docstring?

2024-11-19 06:07 UTC, CoolCat467 commented
Very interested in seeing this go through, I would like to add the rest of the missing type annotations on top of these changes.

2024-11-19 19:06 UTC, ISOR3X commented
> Overall looks pretty good, but I noticed a few things.

Thank you for taking a look at this! Your feedback is much welcomed.
RE: Nuking the data in the `pyproject.toml`; I’m honestly not sure why I did it. I may have forgotten to put them back in when switching over to uv.
RE: The module docstrings; I interpreted these as class docstrings, that might have been a mistake on my end.

For this initial commit I wanted to focus mostly on the syntax and then depending on the response I would like to add more, though some improvements may have already slipped in. I will revert and/or fix some of the mistakes I made soon and will then await approval.

2025-03-20 09:18 UTC, closed without merging

2025-03-20 18:59 UTC, CoolCat467 commented
That's sad to see that this never went through